enum MutationTypes {
  OVERRIDE_REQUEST = 'OVERRIDE_REQUEST',
  OVERRIDE_RAW_REQUEST = 'OVERRIDE_RAW_REQUEST',
  PATCH_REQUEST_HEADER = 'PATCH_REQUEST_HEADER',
  PATCH_REQUEST_METHOD = 'PATCH_REQUEST_METHOD',
}

export default MutationTypes
